'''
Django settings for random_apps project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
'''

from pathlib import Path
from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vbakg690r9bk+7&-j)paac=bq81@ie@qho9k6yx)80=i63l%0z'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'scarecrow',  # Scare off script kiddies
    'b64app',     # Base64 encoder/decoder
    'uploader',   # Uploader
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'random_apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            # BASE_DIR / 'scarecrow' / 'templates',
            # BASE_DIR / 'b64app' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'random_apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'b64app_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'b64app' / 'storage' / 'db.sqlite3',
    },
    'uploader_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'uploader' / 'storage' / 'db.sqlite3',
    },
}
DATABASE_ROUTERS = [
    'b64app.routers.DBRouter',
    'uploader.routers.DBRouter',
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.AppDirectoriesFinder']
STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/admin/login/' # Used by `login_required`
LOGIN_REDIRECT_URL = '/'

# # Ensure cookies are only sent over HTTPS
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# # Prevent client-side JavaScript from accessing cookies
# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_HTTPONLY = True

# # Optionally, enable the SameSite attribute for additional protection (e.g., "Strict" or "Lax")
# SESSION_COOKIE_SAMESITE = "Lax"  # Options: 'Lax', 'Strict', or 'None'
# CSRF_COOKIE_SAMESITE = "Lax"  # Same as above

DOMAIN = 'example.com'
if DOMAIN:
    LOGIN_URL = f"http://admin.{DOMAIN}/login/"

    # https://github.com/jazzband/django-hosts
    # https://dev.to/ksharma20/how-to-use-subdomains-for-different-apps-in-django-project--fbi
    ROOT_HOSTCONF = 'random_apps.hosts'
    DEFAULT_HOST= 'www'
    
    INSTALLED_APPS += ['django_hosts']
    
    ALLOWED_HOSTS = [f'.{DOMAIN}']  # All subdomains of domain
    if DEBUG:
        ALLOWED_HOSTS += ['localhost', '127.0.0.1']  # For local testing
    
    MIDDLEWARE = [
        'django_hosts.middleware.HostsRequestMiddleware',
        *MIDDLEWARE,
        'django_hosts.middleware.HostsResponseMiddleware',
    ]
    
    CSRF_TRUSTED_ORIGINS = [ f'https://*.{DOMAIN}' ]
    
    # Make cookies accessible across all subdomains
    SESSION_COOKIE_DOMAIN = f".{DOMAIN}"
    CSRF_COOKIE_DOMAIN = f".{DOMAIN}"
